apiVersion: v1
kind: ConfigMap
metadata:
  name: mockserver-config
  namespace: mockserver
data:
  mockserver.properties: |
    mockserver.proactivelyInitializeTLT=true
    mockserver.watchInitializationJson=true
    mockserver.initializationJsonPath=/config/initializerJson.json
  initializerJson.json: |
    [
      {
        "httpRequest": {
          "path": "/ping",
          "secure": true
        },
        "httpResponse": {
          "headers": {
            "Content-Type": ["application/json"]
          },
          "body": "{\"ack\":\"ok\"}"
        }
      }
    ]
